// eslint-disable-next-line import/no-unused-modules
export var CheezeWizardsGuild = [
    {
        constant: false,
        inputs: [
            { name: "to", type: "address" },
            { name: "wizardId", type: "uint256" },
        ],
        name: "approve",
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        constant: false,
        inputs: [],
        name: "closeSeries",
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        constant: false,
        inputs: [
            { name: "wizardIds", type: "uint256[]" },
            { name: "powers", type: "uint88[]" },
            { name: "affinities", type: "uint8[]" },
            { name: "owner", type: "address" },
        ],
        name: "mintReservedWizards",
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        constant: false,
        inputs: [
            { name: "powers", type: "uint88[]" },
            { name: "affinities", type: "uint8[]" },
            { name: "owner", type: "address" },
        ],
        name: "mintWizards",
        outputs: [{ name: "wizardIds", type: "uint256[]" }],
        payable: false,
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        constant: false,
        inputs: [
            { name: "minter", type: "address" },
            { name: "reservedIds", type: "uint256" },
        ],
        name: "openSeries",
        outputs: [{ name: "seriesId", type: "uint64" }],
        payable: false,
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        constant: false,
        inputs: [
            { name: "from", type: "address" },
            { name: "to", type: "address" },
            { name: "wizardId", type: "uint256" },
        ],
        name: "safeTransferFrom",
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        constant: false,
        inputs: [
            { name: "from", type: "address" },
            { name: "to", type: "address" },
            { name: "wizardId", type: "uint256" },
            { name: "_data", type: "bytes" },
        ],
        name: "safeTransferFrom",
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        constant: false,
        inputs: [
            { name: "wizardId", type: "uint256" },
            { name: "newAffinity", type: "uint8" },
        ],
        name: "setAffinity",
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        constant: false,
        inputs: [
            { name: "to", type: "address" },
            { name: "approved", type: "bool" },
        ],
        name: "setApprovalForAll",
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        constant: false,
        inputs: [{ name: "newCeo", type: "address" }],
        name: "setCeo",
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        constant: false,
        inputs: [{ name: "newCfo", type: "address" }],
        name: "setCfo",
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        constant: false,
        inputs: [{ name: "newCoo", type: "address" }],
        name: "setCoo",
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        constant: false,
        inputs: [
            { name: "wizardIds", type: "uint256[]" },
            { name: "metadata", type: "bytes32[]" },
        ],
        name: "setMetadata",
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        constant: false,
        inputs: [
            { name: "from", type: "address" },
            { name: "to", type: "address" },
            { name: "wizardId", type: "uint256" },
        ],
        name: "transferFrom",
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [{ name: "_cooAddress", type: "address" }],
        payable: false,
        stateMutability: "nonpayable",
        type: "constructor",
    },
    {
        anonymous: false,
        inputs: [
            { indexed: false, name: "seriesIndex", type: "uint64" },
            { indexed: false, name: "reservedIds", type: "uint256" },
        ],
        name: "SeriesOpen",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [{ indexed: false, name: "seriesIndex", type: "uint64" }],
        name: "SeriesClose",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, name: "wizardId", type: "uint256" },
            { indexed: false, name: "metadata", type: "bytes32" },
        ],
        name: "MetadataSet",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            { indexed: false, name: "from", type: "address" },
            { indexed: false, name: "to", type: "address" },
            { indexed: false, name: "wizardId", type: "uint256" },
        ],
        name: "Transfer",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            { indexed: false, name: "owner", type: "address" },
            { indexed: false, name: "approved", type: "address" },
            { indexed: false, name: "wizardId", type: "uint256" },
        ],
        name: "Approval",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            { indexed: false, name: "owner", type: "address" },
            { indexed: false, name: "operator", type: "address" },
            { indexed: false, name: "approved", type: "bool" },
        ],
        name: "ApprovalForAll",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            { indexed: false, name: "wizardId", type: "uint256" },
            { indexed: false, name: "affinity", type: "uint8" },
            { indexed: false, name: "innatePower", type: "uint256" },
        ],
        name: "WizardConjured",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            { indexed: false, name: "wizardId", type: "uint256" },
            { indexed: false, name: "affinity", type: "uint8" },
        ],
        name: "WizardAffinityAssigned",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            { indexed: false, name: "previousCeo", type: "address" },
            { indexed: false, name: "newCeo", type: "address" },
        ],
        name: "CEOTransferred",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            { indexed: false, name: "previousCoo", type: "address" },
            { indexed: false, name: "newCoo", type: "address" },
        ],
        name: "COOTransferred",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            { indexed: false, name: "previousCfo", type: "address" },
            { indexed: false, name: "newCfo", type: "address" },
        ],
        name: "CFOTransferred",
        type: "event",
    },
    {
        constant: true,
        inputs: [],
        name: "_INTERFACE_ID_ERC165",
        outputs: [{ name: "", type: "bytes4" }],
        payable: false,
        stateMutability: "view",
        type: "function",
    },
    {
        constant: true,
        inputs: [],
        name: "_INTERFACE_ID_INVALID",
        outputs: [{ name: "", type: "bytes4" }],
        payable: false,
        stateMutability: "view",
        type: "function",
    },
    {
        constant: true,
        inputs: [{ name: "owner", type: "address" }],
        name: "balanceOf",
        outputs: [{ name: "", type: "uint256" }],
        payable: false,
        stateMutability: "view",
        type: "function",
    },
    {
        constant: true,
        inputs: [],
        name: "ceoAddress",
        outputs: [{ name: "", type: "address" }],
        payable: false,
        stateMutability: "view",
        type: "function",
    },
    {
        constant: true,
        inputs: [],
        name: "cfoAddress",
        outputs: [{ name: "", type: "address" }],
        payable: false,
        stateMutability: "view",
        type: "function",
    },
    {
        constant: true,
        inputs: [],
        name: "cooAddress",
        outputs: [{ name: "", type: "address" }],
        payable: false,
        stateMutability: "view",
        type: "function",
    },
    {
        constant: true,
        inputs: [
            { name: "_contract", type: "address" },
            { name: "_interfaceId", type: "bytes4" },
        ],
        name: "doesContractImplementInterface",
        outputs: [{ name: "", type: "bool" }],
        payable: false,
        stateMutability: "view",
        type: "function",
    },
    {
        constant: true,
        inputs: [{ name: "wizardId", type: "uint256" }],
        name: "getApproved",
        outputs: [{ name: "", type: "address" }],
        payable: false,
        stateMutability: "view",
        type: "function",
    },
    {
        constant: true,
        inputs: [{ name: "id", type: "uint256" }],
        name: "getWizard",
        outputs: [
            { name: "owner", type: "address" },
            { name: "innatePower", type: "uint88" },
            { name: "affinity", type: "uint8" },
            { name: "metadata", type: "bytes32" },
        ],
        payable: false,
        stateMutability: "view",
        type: "function",
    },
    {
        constant: true,
        inputs: [
            { name: "owner", type: "address" },
            { name: "operator", type: "address" },
        ],
        name: "isApprovedForAll",
        outputs: [{ name: "", type: "bool" }],
        payable: false,
        stateMutability: "view",
        type: "function",
    },
    {
        constant: true,
        inputs: [
            { name: "spender", type: "address" },
            { name: "tokenId", type: "uint256" },
        ],
        name: "isApprovedOrOwner",
        outputs: [{ name: "", type: "bool" }],
        payable: false,
        stateMutability: "view",
        type: "function",
    },
    {
        constant: true,
        inputs: [{ name: "wizardId", type: "uint256" }],
        name: "ownerOf",
        outputs: [{ name: "", type: "address" }],
        payable: false,
        stateMutability: "view",
        type: "function",
    },
    {
        constant: true,
        inputs: [{ name: "interfaceId", type: "bytes4" }],
        name: "supportsInterface",
        outputs: [{ name: "", type: "bool" }],
        payable: false,
        stateMutability: "view",
        type: "function",
    },
    {
        constant: true,
        inputs: [
            { name: "wizardId", type: "uint256" },
            { name: "hash", type: "bytes32" },
            { name: "sig", type: "bytes" },
        ],
        name: "verifySignature",
        outputs: [],
        payable: false,
        stateMutability: "view",
        type: "function",
    },
    {
        constant: true,
        inputs: [
            { name: "wizardId1", type: "uint256" },
            { name: "wizardId2", type: "uint256" },
            { name: "hash1", type: "bytes32" },
            { name: "hash2", type: "bytes32" },
            { name: "sig1", type: "bytes" },
            { name: "sig2", type: "bytes" },
        ],
        name: "verifySignatures",
        outputs: [],
        payable: false,
        stateMutability: "view",
        type: "function",
    },
    {
        constant: true,
        inputs: [{ name: "", type: "uint256" }],
        name: "wizardsById",
        outputs: [
            { name: "affinity", type: "uint8" },
            { name: "innatePower", type: "uint88" },
            { name: "owner", type: "address" },
            { name: "metadata", type: "bytes32" },
        ],
        payable: false,
        stateMutability: "view",
        type: "function",
    },
];
//# sourceMappingURL=CheezeWizardsGuild.js.map