version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "vue",
    "angularjs"
  ]
  environment = [
    "nodejs",
    "browser",
    "jest"
  ]

[[transformers]]
name = "standardjs"

[[transformers]]
name = "prettier"