name: Bug report
description: File a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please ensure that the bug has not already been filed in the issue tracker.

        Thanks for taking the time to report this bug!
  - type: dropdown
    attributes:
      label: Component
      description: What component is the bug in?
      multiple: true
      options:
        - API
        - Utils
        - Other (please describe)
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Have you ensured that all of these are up to date?
      options:
        - label: opensea-js
        - label: Node (minimum v16)
  - type: input
    attributes:
      label: What version of opensea-js are you on?
  - type: input
    attributes:
      label: What function is the bug in?
      description: Leave empty if not relevant
      placeholder: "For example: fulfillOrder"
  - type: dropdown
    attributes:
      label: Operating System
      description: What operating system are you on?
      options:
        - Windows
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Linux
  - type: textarea
    attributes:
      label: Describe the bug
      description: Please include relevant code snippets as well that can recreate the bug.
    validations:
      required: true
