/**
 * AUTO-GENERATED by scripts/sync-chains.ts — DO NOT EDIT.
 * Source of truth: OpenSea REST API + scripts/chain-data.json
 * Run `pnpm sync-chains` to regenerate.
 */

/** Map chain slug (Chain enum value) to numeric chain ID. */
export const CHAIN_ID_MAP: Record<string, string> = {
  ethereum: "1",
  optimism: "10",
  unichain: "130",
  polygon: "137",
  monad: "143",
  shape: "360",
  flow: "747",
  hyperevm: "999",
  sei: "1329",
  soneium: "1868",
  ronin: "2020",
  abstract: "2741",
  megaeth: "4326",
  somnia: "5031",
  b3: "8333",
  base: "8453",
  ape_chain: "33139",
  arbitrum: "42161",
  avalanche: "43114",
  gunzilla: "43419",
  ink: "57073",
  animechain: "69000",
  bera_chain: "80094",
  blast: "81457",
  zora: "7777777",
}
