import { OpenSeaAPI } from "../api";
export declare const MAINNET_API_KEY: string | undefined;
export declare const WALLET_ADDRESS: string | undefined;
export declare const WALLET_PRIV_KEY: string | undefined;
export declare const ALCHEMY_API_KEY: string | undefined;
export declare const mainApi: OpenSeaAPI;
export declare const testnetApi: OpenSeaAPI;
export declare const DAPPER_ADDRESS = "0x4819352bd7fadcCFAA8A2cDA4b2825a9ec51417c";
export declare const BAYC_CONTRACT_ADDRESS = "0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d";
export declare const BAYC_TOKEN_ID = "1";
export declare const BAYC_TOKEN_IDS: string[];
export declare const WETH_ADDRESS = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2";
