import BigNumber from 'bignumber.js'
import * as Web3 from 'web3'
import {
  Network,
  HowToCall,
  SaleKind,
  ECSignature,
  Order as WyvernOrder
} from 'wyvern-js/lib/types'

export {
  Network,
  HowToCall,
  SaleKind,
  ECSignature
}

/**
 * Events emitted by the SDK. There are two types:
 * 1. transaction events, which tell you when a new transaction was
 *    created, confirmed, or failed
 * 2. pre-transaction events, which are named (like "WrapEth") and indicate
 *    that Web3 is asking for a signature on a transaction
 */
export enum EventType {
  TransactionCreated = "TransactionCreated",
  TransactionConfirmed = "TransactionConfirmed",
  TransactionFailed = "TransactionFailed",

  InitializeAccount = "InitializeAccount",

  WrapEth = "WrapEth",
  UnwrapWeth = "UnwrapWeth",

  ApproveCurrency = "ApproveCurrency",
  ApproveAsset = "ApproveAsset",
  ApproveAllAssets = "ApproveAllAssets",

  MatchOrders = "MatchOrders",
  CancelOrder = "CancelOrder",
}

/**
 * Data that gets sent with each EventType
 */
export interface EventData {
  accountAddress?: string
  proxyAddress?: string
  amount?: BigNumber
  tokenAddress?: string
  tokenId?: string

  transactionHash?: string
  event?: EventType
  error?: Error

  order?: Order
  buy?: Order
  sell?: Order
}

export interface OpenSeaAPIConfig {
  networkName?: Network
  apiKey?: string
  // Sent to WyvernJS
  gasPrice?: BigNumber
}

/**
 * Wyvern order side: buy or sell.
 */
export enum OrderSide {
  Buy = 0,
  Sell = 1,
}

/**
 * Wyvern fee method
 */
export enum FeeMethod {
  /* Charge maker fee to seller and charge taker fee to buyer. */
  ProtocolFee = 0,
  /* Maker fees are deducted from the token amount that the maker receives. Taker fees are extra tokens that must be paid by the taker. */
  SplitFee = 1,
}

export interface WyvernAsset {
  id: string
  address: string
}

/**
 * The OpenSea account object appended to orders, providing extra metadata, profile images and usernames
 */
export interface OpenSeaAccount {
  // Wallet address for this account
  address: string
  // Public configuration info, including "affiliate" for users who are in the OpenSea affiliate program
  config: string
  // This account's profile image - by default, randomly generated by the server
  profile_img_url: string

  // More information explicitly set by this account's owner on OpenSea
  user: null | {
    // Username for this account
    username: string;
  }
}

export interface UnhashedOrder extends WyvernOrder {
  feeMethod: FeeMethod
  side: OrderSide
  saleKind: SaleKind
  howToCall: HowToCall

  metadata: {
    asset: WyvernAsset;
    schema: SchemaName;
  }
}

export interface UnsignedOrder extends UnhashedOrder {
  hash: string
}

export interface Order extends UnsignedOrder, ECSignature {
  // Server side appends
  makerAccount?: OpenSeaAccount,
  takerAccount?: OpenSeaAccount,
  feeRecipientAccount?: OpenSeaAccount,
  cancelledOrFinalized?: boolean
  markedInvalid?: boolean
  currentPrice?: BigNumber
  asset?: {
    owner: OpenSeaAccount;
  }
}

export interface OrderJSON {
  exchange: string
  maker: string
  taker: string
  makerRelayerFee: string
  takerRelayerFee: string
  makerProtocolFee: string
  takerProtocolFee: string
  feeRecipient: string
  feeMethod: FeeMethod
  side: OrderSide
  saleKind: SaleKind
  target: string
  howToCall: HowToCall
  calldata: string
  replacementPattern: string
  staticTarget: string
  staticExtradata: string
  paymentToken: string
  basePrice: string
  extra: string
  listingTime: string
  expirationTime: string
  salt: string

  metadata: {
    asset: WyvernAsset;
    schema: SchemaName;
  }

  // Optional, so that we can JSONify orders before sending them to getOrderHashHex
  hash?: string
  v?: number
  r?: string
  s?: string

  // Used by orderbook to make queries easier
  owner?: string,
  asset_contract_address?: string,
  token_id?: number | string
  limit?: number
  offset?: number
}

export interface OrderbookResponse {
  orders: OrderJSON[]
  count: number
}

/**
 * Types related to Web3
 */

export type Web3Callback<T> = (err: Error | null, result: T) => void
export type Web3RPCCallback = Web3Callback<Web3.JSONRPCResponsePayload>
export type TxnCallback = (result: boolean) => void

// To simplify typifying ABIs:
export interface PartialAbiDefinition {
  type: Web3.AbiType | string // Not Partial!
  name?: string
  inputs?: object[]
  outputs?: object[]
  payable?: boolean
  constant?: boolean
  anonymous?: boolean
  stateMutability?: Web3.ConstructorStateMutability | string
}
export type PartialReadonlyContractAbi = Array<Readonly<PartialAbiDefinition>>
