name: Node.js Package

on:
  release:
    types: [published]

jobs:
  publish:
    uses: ./.github/workflows/npm-publish-reusable.yml
    with:
      stub-package-dir: packages/opensea-js-stub
    secrets: inherit
